# Generated by Django 5.1.4 on 2025-02-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loginattempt',
            name='login_attem_usernam_46c78a_idx',
        ),
        migrations.RenameField(
            model_name='loginattempt',
            old_name='username',
            new_name='email',
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['email', 'ip_address'], name='login_attem_email_374346_idx'),
        ),
    ]
