# Generated by Django 5.1.4 on 2025-02-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_remove_loginattempt_login_attem_usernam_46c78a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
