# Generated by Django 5.1.4 on 2025-02-10 22:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, null=True)),
                ('authors', models.JSONField(default=list, null=True)),
                ('publication_date', models.DateField(null=True)),
                ('publisher', models.CharField(max_length=200, null=True)),
                ('doi', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(max_length=500, null=True)),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('citation', models.TextField(null=True)),
                ('reference', models.JSONField(default=dict, null=True)),
                ('summary', models.TextField(null=True)),
                ('total_pages', models.IntegerField(null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('processing_progress', models.FloatField(default=0.0)),
                ('processing_stage', models.CharField(max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_metadata',
            },
        ),
        migrations.CreateModel(
            name='DocumentRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relationships', to='research_assistant.documentmetadata')),
                ('target_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relationships', to='research_assistant.documentmetadata')),
            ],
            options={
                'db_table': 'document_relationships',
            },
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('section_type', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('section_start_page_number', models.IntegerField()),
                ('prev_page_text', models.TextField(null=True)),
                ('next_page_text', models.TextField(null=True)),
                ('has_citations', models.BooleanField(default=False)),
                ('has_tables', models.BooleanField(default=False)),
                ('has_images', models.BooleanField(default=False)),
                ('citations', models.JSONField(default=dict)),
                ('tables', models.JSONField(null=True)),
                ('images', models.JSONField(default=list)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='research_assistant.documentmetadata')),
            ],
            options={
                'db_table': 'document_sections',
                'ordering': ['section_start_page_number'],
            },
        ),
        migrations.CreateModel(
            name='LLMResponseCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('response_type', models.CharField(max_length=50)),
                ('query_hash', models.TextField()),
                ('response_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_responses', to='research_assistant.documentmetadata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'llm_response_cache',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documents', models.ManyToManyField(related_name='searches', to='research_assistant.documentmetadata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_queries',
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('query_context', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('document_title', models.CharField(max_length=500)),
                ('document_authors', models.JSONField(default=list)),
                ('document_summary', models.TextField(null=True)),
                ('relevance_score', models.FloatField()),
                ('matching_sections', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_assistant.documentmetadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_results',
            },
        ),
        migrations.AddIndex(
            model_name='documentmetadata',
            index=models.Index(fields=['user'], name='document_me_user_id_a4d031_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmetadata',
            index=models.Index(fields=['processing_status'], name='document_me_process_44c47a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmetadata',
            index=models.Index(fields=['created_at'], name='document_me_created_0aa4db_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmetadata',
            index=models.Index(fields=['updated_at'], name='document_me_updated_4336e5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrelationship',
            index=models.Index(fields=['source_document', 'target_document'], name='document_re_source__2718f5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrelationship',
            index=models.Index(fields=['relationship_type'], name='document_re_relatio_035f14_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrelationship',
            index=models.Index(fields=['confidence_score'], name='document_re_confide_a70bea_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsection',
            index=models.Index(fields=['document', 'section_start_page_number'], name='document_se_documen_f8df54_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsection',
            index=models.Index(fields=['section_type'], name='document_se_section_206ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='llmresponsecache',
            index=models.Index(fields=['user'], name='llm_respons_user_id_087e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='llmresponsecache',
            index=models.Index(fields=['document', 'response_type', 'query_hash'], name='llm_respons_documen_bc5eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='llmresponsecache',
            index=models.Index(fields=['created_at'], name='llm_respons_created_e754e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='llmresponsecache',
            unique_together={('user', 'document', 'response_type', 'query_hash')},
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['user'], name='search_quer_user_id_64dda1_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['created_at'], name='search_quer_created_02141d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['user'], name='search_resu_user_id_be789f_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['document'], name='search_resu_documen_2c591c_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['created_at'], name='search_resu_created_51526a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['relevance_score'], name='search_resu_relevan_75610c_idx'),
        ),
    ]
