# Generated by Django 5.1.1 on 2025-01-03 00:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, null=True)),
                ('authors', models.JSONField(default=list, null=True)),
                ('publication_date', models.DateField(null=True)),
                ('publisher', models.CharField(max_length=200, null=True)),
                ('doi', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(max_length=500, null=True)),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('citation', models.TextField(null=True)),
                ('reference', models.JSONField(default=dict, null=True)),
                ('summary', models.TextField(null=True)),
                ('total_pages', models.IntegerField(null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('processing_progress', models.FloatField(default=0.0)),
                ('processing_stage', models.CharField(max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_metadata',
                'indexes': [models.Index(fields=['processing_status'], name='document_me_process_44c47a_idx'), models.Index(fields=['created_at'], name='document_me_created_0aa4db_idx'), models.Index(fields=['updated_at'], name='document_me_updated_4336e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('section_type', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('section_start_page_number', models.IntegerField()),
                ('position', models.IntegerField()),
                ('title_group_number', models.IntegerField(null=True)),
                ('title_group_text', models.TextField(null=True)),
                ('start_text', models.CharField(max_length=200)),
                ('section_id', models.CharField(max_length=100)),
                ('url_fragment', models.CharField(max_length=200)),
                ('has_citations', models.BooleanField(default=False)),
                ('has_tables', models.BooleanField(default=False)),
                ('has_figures', models.BooleanField(default=False)),
                ('has_images', models.BooleanField(default=False)),
                ('citations', models.JSONField(default=dict)),
                ('table_data', models.JSONField(null=True)),
                ('elements', models.JSONField(default=list)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='research_assistant.documentmetadata')),
            ],
            options={
                'db_table': 'document_sections',
                'ordering': ['section_start_page_number', 'position'],
                'indexes': [models.Index(fields=['document', 'section_start_page_number'], name='document_se_documen_f8df54_idx'), models.Index(fields=['section_type'], name='document_se_section_206ad4_idx')],
            },
        ),
    ]
