# Generated by Django 5.1.1 on 2024-11-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmetadata',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
