# Generated by Django 5.1.4 on 2025-03-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_assistant', '0002_searchresult_processing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
