# Generated by Django 5.1.4 on 2025-03-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_assistant', '0003_searchresult_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmetadata',
            name='citation',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
