# Generated by Django 5.1.4 on 2025-01-17 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_assistant', '0003_documentsection_extracted_image_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsection',
            options={'ordering': ['section_start_page_number']},
        ),
        migrations.RenameField(
            model_name='documentsection',
            old_name='elements',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='documentsection',
            old_name='extracted_image_text',
            new_name='next_page_text',
        ),
        migrations.RenameField(
            model_name='documentsection',
            old_name='title_group_text',
            new_name='prev_page_text',
        ),
        migrations.RenameField(
            model_name='documentsection',
            old_name='table_data',
            new_name='tables',
        ),
        migrations.RemoveField(
            model_name='documentsection',
            name='has_figures',
        ),
        migrations.RemoveField(
            model_name='documentsection',
            name='position',
        ),
        migrations.RemoveField(
            model_name='documentsection',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='documentsection',
            name='start_text',
        ),
        migrations.RemoveField(
            model_name='documentsection',
            name='title_group_number',
        ),
        migrations.RemoveField(
            model_name='documentsection',
            name='url_fragment',
        ),
    ]
