# Generated by Django 5.1.4 on 2025-01-19 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_assistant', '0004_alter_documentsection_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='searchquery',
            name='search_quer_theme_a0301c_idx',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='theme_matches',
        ),
    ]
