# Generated by Django 5.1.4 on 2025-03-18 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_assistant', '0004_alter_documentmetadata_citation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('document_id', models.CharField(blank=True, max_length=500, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=500, null=True)),
                ('citations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notes_user_id_e4f281_idx'), models.Index(fields=['document_id'], name='notes_documen_b980a5_idx')],
            },
        ),
    ]
