# Generated by Django 5.1.4 on 2025-01-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_assistant', '0005_remove_searchquery_search_quer_theme_a0301c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmresponsecache',
            name='file_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
