# Generated by Django 5.1.4 on 2025-03-29 00:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_assistant', '0006_researchcontext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAPIUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('prompt', models.TextField(null=True)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost_per_1k_prompt_tokens', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cost_per_1k_completion_tokens', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('is_aggregated', models.BooleanField(default=False)),
                ('api_calls_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_usages', to='research_assistant.documentmetadata')),
                ('search_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_usages', to='research_assistant.searchresult')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_api_usage',
                'indexes': [models.Index(fields=['user'], name='ai_api_usag_user_id_2d77f0_idx'), models.Index(fields=['search_result'], name='ai_api_usag_search__bf6f4b_idx'), models.Index(fields=['model_name'], name='ai_api_usag_model_n_e84f39_idx'), models.Index(fields=['created_at'], name='ai_api_usag_created_89586a_idx')],
            },
        ),
    ]
