# Generated by Django 5.1.4 on 2025-04-01 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_assistant', '0007_aiapiusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('research_area', models.JSONField(default=dict)),
                ('themes', models.JSONField(default=list)),
                ('chronological_development', models.JSONField(default=dict)),
                ('theoretical_frameworks', models.JSONField(default=dict)),
                ('methodological_approaches', models.JSONField(default=dict)),
                ('key_findings', models.JSONField(default=list)),
                ('method_strengths', models.JSONField(default=list)),
                ('method_limitations', models.JSONField(default=list)),
                ('result_strengths', models.JSONField(default=list)),
                ('result_weaknesses', models.JSONField(default=list)),
                ('potential_biases', models.JSONField(default=list)),
                ('extraction_time', models.FloatField(null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literature_reviews', to='research_assistant.documentmetadata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'literature_reviews',
                'indexes': [models.Index(fields=['document'], name='literature__documen_41f03c_idx'), models.Index(fields=['user'], name='literature__user_id_16fa7f_idx'), models.Index(fields=['processing_status'], name='literature__process_748ef4_idx'), models.Index(fields=['created_at'], name='literature__created_8f239b_idx')],
            },
        ),
    ]
